name: Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{secrets.PAT}}
    - name: Build
      run: |
        cd webdev
        npm install
        npm run build
        cd ..
        rm -rf webdev
        sed -i '$d' .gitignore
        git checkout -b build
        git add .
        git commit -m "Build"
        git push origin build
    
